### ISSUE TITLE
error with your own example....

### ISSUE THREAD

**Issue by cryptid11** [AnthonyBloomer/pyflights#1]
Traceback (most recent call last):
  File "flight.py", line 12, in <module>
    'solutions': 1
  File "/usr/local/lib/python2.7/dist-packages/pyflights/pyflight.py", line 14, in search
    [flights.append(Flight(res)) for res in req['trips']['tripOption']]
KeyError: 'trips'

**Comment by AnthonyBloomer** [comment]
Hi, it may be because my example is using a past date or else you have provided an invalid key.

**Comment by cryptid11** [comment]
yes, sorry, my fault, now only problem is
AttributeError: 'Flight' object has no attribute 'flight_airline'

**Comment by AnthonyBloomer** [comment]
@cryptid11 it should be flight_carrier not flight_airline. I've updated the documentation. Hope that helps.
